### ISSUE TITLE
NotificationReceived delegate not always being called

### ISSUE THREAD

**Issue by dwarffrench** [OneSignal/OneSignal-WindowsPhone-SDK#2]
Hello,

I am having an issue with my NotificationReceived delegate. It only gets called when the application is in foreground when the notification is received or when it is not launched before clicking on the notification.
If the application is in background when the notification is clicked, the delegate does not get called.

I have checked the provided sample code and this bug does not happen.

So this issue is most definitely from my implementation of OneSignal or the application code. Do you any clues/ideas ?

**Comment by jkasten2** [comment]
@dwarffrench Just to confirm you are using our Windows Phone 8.1 SDK (WNS)?

It may not work in your app if you are removing our listener from VisibilityChanged.
https://github.com/OneSignal/OneSignal-WindowsPhone-SDK/blob/master/Source/OneSignalSDK_WP_WNS/OneSignal.cs#L73

Thanks.

**Comment by dwarffrench** [comment]
Sorry, I forgot to provide you with that information... 
As the minimum supported OS version is 8.0, I am using your Windows Phone 8.0 SDK (OneSignalSDK_WP8.0)

**Comment by jkasten2** [comment]
@dwarffrench Can you try adding some debugging to our SDK to see if it is firing for you?
https://github.com/OneSignal/OneSignal-WindowsPhone-SDK/blob/master/Source/OneSignalSDK_WP8.0/OneSignal.cs#L85

Print out `startingPage.NavigationContext.QueryString` to make sure the payload is getting to your app as well.

**Comment by dwarffrench** [comment]
@jkasten2 I have added the debugging you asked. When the app is not running in background and I open it by tapping a push notification, the method is firing. I added some additional data to the notification to try and the payload (seen below) is correct.
`QueryString:
GameThriveParams={"custom":{"i":"5c214c76-89e0-4033-aea8-2e83b1975d25","a":{"additional":"data"}}}`

However when the application is in background, the method is never fired.

I wondered if this could be caused by the activation policy we set for our app in the WMAppManifest (`ActivationPolicy="Resume"`) which could cause your SDK to not detect the notification open. So I tested our app without this activation policy and the method is fired every time. 

Can you think of a work-around to disabling this activation policy, as we prefer to keep it as is ?

**Comment by dwarffrench** [comment]
Hey, just saw I forgot to close the issue. 
I ended up disabling the ActivationPolicy and everything works fine !
